[[plugins]]
repo = 'ayu-theme/ayu-vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
merged = '0'
rev = 'release'
#hook_add='''
#'''

#[[plugins]]
#repo = 'honza/vim-snippets'

[[plugins]]
repo = 'voldikss/vim-floaterm'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'tyru/caw.vim'

#
# Git
#
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
set updatetime=100
'''

[[plugins]]
repo = 'lambdalisue/gina.vim'

#
# icon (tablineにつけてくれる)
# あとで設定を変える
#
[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = '''
    let g:webdevicons_enable_nerdtree = 1
    let g:WebDevIconsUnicodeDecorateFolderNodes = 1
    let g:WebDevIconsNerdTreeAfterGlyphPadding = ' '
    let g:WebDevIconsNerdTreeBeforeGlyphPadding = ' '
    let g:WebDevIconsUnicodeGlyphDoubleWidth = 1
    " let g:WebDevIconsOS = 'Darwin'
    " let g:webdevicons_conceal_nerdtree_brackets = 0
'''

#
# htmlのclose tag
#
[[plugins]]
repo = 'alvan/vim-closetag'
hook_add = '''
let g:closetag_filenames = '*.html,*.vue'
'''

#
# Terminal
#
[[plugins]]
repo = 'kassio/neoterm'


#
# ファイラー
#
[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'

[[plugins]]
repo = 'lambdalisue/fern.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-devicons.vim'
hook_add = '''
let g:fern#renderer = "devicons"
'''

[[plugins]]
repo = 'LumaKernel/fern-mapping-fzf.vim'
depends = ['fzf', 'fern.vim']
hook_add = '''
let s:dein_cache = expand('~/.cache/vim/dein')
if has('nvim')
  let s:dein_cache = expand('~/.cache/nvim/dein')
endif

let s:bin_dir = s:dein_cache . '/repos/github.com/junegunn/fzf.vim/bin/preview.sh'
let s:preview_command = s:bin_dir . ' {}'
let g:fern#mapping#fzf#fzf_options = {'options': ['--layout=reverse', '--info=inline', '--preview', s:preview_command ]}
'''

[[plugins]]
repo = 'kassio/neoterm'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = 'fzf'
#hook_add = '''
#set rtp+=/usr/local/opt/fzf
#'''

[[plugins]]
repo = 'lambdalisue/fern.vim'

[[plugins]]
repo = 'lambdalisue/fern-renderer-devicons.vim'
hook_add = '''
let g:gern#render = "devicons"
'''

[[plugins]]
repo = 'LumaKernel/fern-mapping-fzf.vim'
depends = ['fzf', 'fern.vim']
hook_add = '''
let s:dein_cache = expand('~/.cache/vim/dein')
if has('nvim')
  let s:dein_cache = expand('~/.cache/nvim/dein')
endif

let s:bin_dir = s:dein_cache . '/repos/github.com/junegunn/fzf.vim/bin/preview.sh'
let s:preview_command = s:bin_dir . ' {}'
let g:fern#mapping#fzf#fzf_options = {'options': ['--layout=reverse', '--info=inline', '--preview', s:preview_command]}
'''


#
# session
#
#[[plugins]]
#repo = 'skanehira/vsession'
#depends = 'fzf'
#hook_add = '''
#let g:vsession_path = '~/.vim/sessions'
#let g:vsession_use_fzf = 1
#'''

#[[plugins]]
#repo = 'xolox/vim-misc'
#
#[[plugins]]
#repo = 'xolox/vim-session'
#depends = 'vim-misc'
#hook_add = '''
#let g:session_autosave = 'no'
#let g:session_autoload = 'no'
#'''

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
