[[plugins]]
repo = 'ayu-theme/ayu-vim'

[[plugins]]
repo = 'neoclide/coc.nvim'
merged = '0'
rev = 'release'
#hook_add='''
#'''

#[[plugins]]
#repo = 'honza/vim-snippets'

[[plugins]]
repo = 'voldikss/vim-floaterm'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

#
# Git
#
[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
set updatetime=100
'''

#
# icon (tablineにつけてくれる)
# あとで設定を変える
#
[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = '''
    let g:webdevicons_enable_nerdtree = 1
    let g:WebDevIconsUnicodeDecorateFolderNodes = 1
    let g:WebDevIconsNerdTreeAfterGlyphPadding = ' '
    let g:WebDevIconsNerdTreeBeforeGlyphPadding = ' '
    let g:WebDevIconsUnicodeGlyphDoubleWidth = 1
    let g:WebDevIconsOS = 'Darwin'
    " let g:webdevicons_conceal_nerdtree_brackets = 0
'''

[[plugins]]
repo = 'alvan/vim-closetag'
hook_add = '''
let g:closetag_filenames = '*.html,*.vue'
'''

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
