#!/bin/bash 

rm "$HOME/.zsh"
rm "$HOME/.zshrc"
rm "$HOME/.zlogin"
rm "$HOME/.bashrc"
rm "$HOME/.cache"
rm "$HOME/.gitconfig"
rm "$HOME/.ssh"
rm "$HOME/.tmux.conf"
rm "$HOME/.config/nvim"

ln -s "$(pwd)/zsh" "$HOME/.zsh"
ln -s "$(pwd)/zsh/zshrc" "$HOME/.zshrc"
ln -s "$(pwd)/zsh/zlogin" "$HOME/.zlogin"
ln -s "$(pwd)/bashrc" "$HOME/.bashrc"
ln -s "$(pwd)/cache" "$HOME/.cache"
ln -s "$(pwd)/gitconfig" "$HOME/.gitconfig"
ln -s "$(pwd)/ssh" "$HOME/.ssh"
ln -s "$(pwd)/tmux/tmux.conf" "$HOME/.tmux.conf"
ln -s "$(pwd)/config/nvim" "$HOME/.config/nvim"
