[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
let g:ale_completion_enabled = 1
"let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_text_changed = 0
let g:ale_lint_on_enter = 0
let g:ale_lint_on_save = 1

let g:ale_set_loclist = 0
let g:ale_set_quickfix = 1
let g:ale_sign_column_always = 1
let g:ale_open_list = 1
let g:ale_keep_list_window_open = 0

let g:ale_linters = {'go': ['gometalinter']}
let g:ale_go_gometalinter_options = '--fast --enable=staticcheck --enable=gosimple --enable=unused'
'''

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]] # hook_add highlight
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

#[[plugins]] # hook highlight
#repo = 'inkarkat/vim-SyntaxRange'

[[plugins]]
repo = 'terryma/vim-expand-region'
hook_add = '''
  vmap v <Plug>(expand_region_expand)
  vmap <C-v> <Plug>(expand_region_shrink)
'''

[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = '''
  let g:tagbar_width = 30
  let g:tagbar_autoshowtag = 1
  let g:tagbar_show_linenumbers = 1
  let g:tagbar_sort = 0
  let g:tagbar_left = 1
  "let g:tagbar_ctags_bin = '/Users/joo/go/bin/gotags'
  let g:tagbar_type_go = {
  	\ 'ctagstype' : 'go',
  	\ 'kinds'     : [
  		\ 'p:package',
  		\ 'i:imports:1',
  		\ 'c:constants',
  		\ 'v:variables',
  		\ 't:types',
  		\ 'n:interfaces',
  		\ 'w:fields',
  		\ 'e:embedded',
  		\ 'm:methods',
  		\ 'r:constructor',
  		\ 'f:functions'
  	\ ],
  	\ 'sro' : '.',
  	\ 'kind2scope' : {
  		\ 't' : 'ctype',
  		\ 'n' : 'ntype'
  	\ },
  	\ 'scope2kind' : {
  		\ 'ctype' : 't',
  		\ 'ntype' : 'n'
  	\ },
  	\ 'ctagsbin'  : 'gotags',
  	\ 'ctagsargs' : '-sort -silent'
  \ }
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  map <C-n> :NERDTreeToggle<CR>
  let g:NERDTreeDirArrowExpandable = '▸'
  let g:NERDTreeDirArrowCollapsible = '▾'
'''

# generate template code
[[plugins]]
repo = 'mattn/sonictemplate-vim'
#hook_add = '''
#let g:snoictemplate_vim_template_dir = ['$HOME/.cache/dein/repos/github.com/mattn/sonictemplate-vim/template']
#'''
