#cat ~/Work/doc/asciiart/toonlink.ascii
#pixterm -tc 80 -tr 35 ~/Work/doc/picture/公式絵_SP_トゥーンリンク.png

if [ "$TERM_PROGRAM" != "Apple_Terminal" ] || [ -n "$TMUX" ]; then
  pixterm ~/Work/doc/picture/公式絵_SP_トゥーンリンク.png
fi
