# autoload
autoload -Uz colors && colors
autoload -Uz compinit && compinit


###################################################
#
#    export
#
###################################################

export HISTFILE=~/.histfile
export HISTSIZE=100000
export SAVEHIST=100000

export LANG=en_US.UTF-8


export TERM="xterm-256color"
export PATH="$PATH:/Users/joo/Work/bin"

export LESSOPEN="| src-hilite-lesspipe.sh %s"
export LESS='-R'
