[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_source = '''
augroup GoCommands
  autocmd!
  autocmd FileType go nnoremap <Leader>r  :<C-U>ReGoRun<CR>
  autocmd FileType go nnoremap <Leader>c  :<C-U>KillGoRunResult<CR>
augroup END

command! -nargs=0 ReGoRun call ReCallGoRun()
function! ReCallGoRun()
  call KillGoRunResult()
  call go#cmd#Run(!g:go_jump_to_error)
endfunction

command! -nargs=0 KillGoRunResult call KillGoRunResult()
function! KillGoRunResult()
  let s:bf_name = bufname('go run')
  if s:bf_name == ""
    return
  endif
  let s:bf = bufnr(s:bf_name)
  execute 'bdelete! ' . s:bf
endfunction
'''

[[plugins]]
repo = 'deoplete-plugins/deoplete-go'
build = 'make'
on_ft = 'go'
hook_add = '''
  let g:deoplete#sources#go#gocode_binary = expand('~/go/src/github.com/stamblerre/gocode')
'''

[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'
# hook_add = '''
# set iskeyword+=$
# set iskeyword+=-
# autocmd MyAutoCmd FileType vue syntax sync fromstart
# let g:ft = ''
# function! NERDCommenter_before()
#   if &ft == 'vue'
#     let g:ft = 'vue'
#     let stack = synstack(line('.'), col('.'))
#     if len(stack) > 0
#       let syn = synIDattr((stack)[0], 'name')
#       if len(syn) > 0
#         exe 'setf ' . substitute(tolower(syn), '^vue_', '', '')
#       endif
#     endif
#   endif
# endfunction
# function! NERDCommenter_after()
#   if g:ft == 'vue'
#     setf vue
#     let g:ft = ''
#   endif
# endfunction
# '''

[[plugins]]
repo = 'vim-jp/vimdoc-ja'
on_ft = ['help']
hook_source = '''
  set helplang=ja,en
'''

[[plugins]]
repo = 'diepm/vim-rest-console'
on_ft = 'rest'


[[plugins]]
repo = 'previm/previm'
on_ft = 'md'
hook_source = '''
  let g:previm_open_cmd = 'open -a firefox'
'''

[[plugins]]
repo = 'seeamkhan/robotframework-vim'
on_ft = 'robot'
