# 現在コードのfiletypeの判定(他のプラグインから使用されることを想定)
[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# snippet機能を追加
#   context_filetype => 文脈に合わせたスニペットを提供
#   neosnippet-snippets => 用意しているスニペットを提供
[[plugins]]
repo = 'Shougo/neosnippet.vim'
depends = ['neosnippet-snippets', 'context_filetype']
on_event = 'InsertCharPre'
on_ft = 'snippet'
hook_add = '''
imap <C-k> <Plug>(neosnippet_expand_or_jump)
smap <C-k> <Plug>(neosnippet_expand_or_jump)
xmap <C-k> <Plug>(neosnippet_expand_target)
let g:neosnippet#enable_snipmate_compatibility = 1
"let g:neosnippet#enable_completed_snippet = 1
"let g:neosnippet#expand_word_boundary = 1
if has('conceal')
  set conceallevel=2 concealcursor=i
endif
'''

# dark powered neo-completionの略
# 非同期の補完フレームワーク
[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = ['context_filetype.vim']
 on_event = 'InsertEnter'
hook_source = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#auto_complete_delay = 0
"  let g:deoplete#auto_complete_start_length = 1
"  let g:deoplete#enable_camel_case = 0
"  let g:deoplete#enable_ignore_case = 0
"  let g:deoplete#enable_refresh_always = 0
"  let g:deoplete#enable_smart_case = 1
"  let g:deoplete#file#enable_buffer_path = 1
  let g:deoplete#max_list = 10000
'''

[[plugins]]
repo = 'autozimu/LanguageClient-neovim'
rev = 'next'
build = 'bash install.sh'
hook_add = '''
set hidden
let g:LanguageClient_serverCommands = {
    \ 'vue': ['vls'],
    \ }

nnoremap <F5> :call LanguageClient_contextMenu()<CR>
nnoremap <silent> <Space>lh :call LanguageClient_textDocument_hover()<CR>
nnoremap <silent> <Space>ld :call LanguageClient_textDocument_definition()<CR>
nnoremap <silent> <Space>lr :call LanguageClient_textDocument_rename()<CR>
nnoremap <silent> <Space>lf :call LanguageClient_textDocument_formatting()<CR>
'''

[[plugins]]
repo = 'posva/vim-vue'
hook_add = '''
autocmd FileType vue syntax sync fromstart
'''

# ---
[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
let g:ale_completion_enabled = 1
"let g:ale_lint_on_text_changed = 'never'
let g:ale_lint_on_text_changed = 0
let g:ale_lint_on_enter = 0
let g:ale_lint_on_save = 1

let g:ale_set_loclist = 0
let g:ale_set_quickfix = 1
let g:ale_sign_column_always = 1
let g:ale_open_list = 1
let g:ale_keep_list_window_open = 0

let g:ale_linters = {
  \ 'go': ['gometalinter'],
  \ 'python': ['flake8'],
  \}
let g:ale_go_gometalinter_options = '--fast --enable=staticcheck --enable=gosimple --enable=unused'
'''

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]] # hook_add highlight
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

#[[plugins]] # hook highlight
#repo = 'inkarkat/vim-SyntaxRange'

[[plugins]]
repo = 'terryma/vim-expand-region'
hook_add = '''
  vmap v <Plug>(expand_region_expand)
  vmap <C-v> <Plug>(expand_region_shrink)
'''

[[plugins]]
repo = 'majutsushi/tagbar'
hook_add = '''
  let g:tagbar_width = 30
  let g:tagbar_autoshowtag = 1
  let g:tagbar_show_linenumbers = 1
  let g:tagbar_sort = 0
  let g:tagbar_left = 1
  "let g:tagbar_ctags_bin = '/Users/joo/go/bin/gotags'
  let g:tagbar_type_go = {
  	\ 'ctagstype' : 'go',
  	\ 'kinds'     : [
  		\ 'p:package',
  		\ 'i:imports:1',
  		\ 'c:constants',
  		\ 'v:variables',
  		\ 't:types',
  		\ 'n:interfaces',
  		\ 'w:fields',
  		\ 'e:embedded',
  		\ 'm:methods',
  		\ 'r:constructor',
  		\ 'f:functions'
  	\ ],
  	\ 'sro' : '.',
  	\ 'kind2scope' : {
  		\ 't' : 'ctype',
  		\ 'n' : 'ntype'
  	\ },
  	\ 'scope2kind' : {
  		\ 'ctype' : 't',
  		\ 'ntype' : 'n'
  	\ },
  	\ 'ctagsbin'  : 'gotags',
  	\ 'ctagsargs' : '-sort -silent'
  \ }
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
  map <C-n> :NERDTreeToggle<CR>
  let g:NERDTreeDirArrowExpandable = '▸'
  let g:NERDTreeDirArrowCollapsible = '▾'
'''

# generate template code
[[plugins]]
repo = 'mattn/sonictemplate-vim'
#hook_add = '''
#let g:snoictemplate_vim_template_dir = ['$HOME/.cache/dein/repos/github.com/mattn/sonictemplate-vim/template']
#'''
