[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
  let g:lightline = {
    \ 'colorscheme': 'wombat', 
    \ }

  let g:lightline.component = {
    \   'helloworld': 'Hello, world!'
    \ }

  let g:lightline.active = {
    \   'left': [ [ 'mode', 'paste' ],
    \             [ 'readonly', 'filename', 'modified' ],
    \             [ 'linter_checking', 'linter_errors', 'linter_warnings', 'linter_ok' ]]
    \ }

  let g:lightline.tab = {
		\ 'active': [ 'tabnum', 'filename', 'filetype', 'modified' ],
		\ 'inactive': [ 'tabnum', 'filename', 'filetype', 'modified' ] 
    \ }

  let g:lightline.tabline = {
		\ 'left': [ [ 'tabs' ] ],
		\ 'right': [ [ 'close' ], [ 'session' ] ] 
    \ }

  let g:lightline.tab_component_function = {
    \       'linter_warnings': 'lightline#ale#warnings',
    \       'linter_errors': 'lightline#ale#errors',
    \       'linter_ok': 'lightline#ale#ok',
    \ }

  function! LightlineTabFilename(n) abort
    let buflist = tabpagebuflist(a:n)
    let winnr = tabpagewinnr(a:n)
    let _ = pathshorten(expand('#'.buflist[winnr - 1].':f'))
    return _ !=# '' ? _ : '[No Name]'
  endfunction

	let g:lightline.component_expand = {
	  \ 'tabs': 'lightline#tabs' 
    \ }

  set laststatus=2
  set noshowmode
''' 

[[plugins]]
repo = 'maximbaz/lightline-ale'
depends = ['lightline.vim', 'ale']
hook_add = '''
let g:lightline.component_expand = {
      \  'linter_checking': 'lightline#ale#checking',
      \  'linter_warnings': 'lightline#ale#warnings',
      \  'linter_errors': 'lightline#ale#errors',
      \  'linter_ok': 'lightline#ale#ok',
      \ }
let g:lightline.component_type = {
      \     'linter_checking': 'left',
      \     'linter_warnings': 'warning',
      \     'linter_errors': 'error',
      \     'linter_ok': 'left',
      \ }
'''

[[plugins]]
repo = 'edkolev/tmuxline.vim'
depends = ['lightline.vim']
